### ISSUE TITLE
您好，需要安装通达信软件吧，安装哪个版本呢？

### ISSUE THREAD

**Issue by bergkamp2008999** [wkingnet/stock-analysis#1]

**Comment by wkingnet** [comment]
这个 http://www.goodgupiao.com/soft/gupiaohangqing/down-61096.html

通达信开心果版本就可以。杀毒软件可能会误报，不放心的话，用虚拟机运行。然后下载盘后数据后，自己复制出来

**Comment by rovertang** [comment]
hoho，bing了半天还只是08版，结果给的链接直接10版了。给力啊。
