### ISSUE TITLE
股本变迁

### ISSUE THREAD

**Issue by 123xy123** [wkingnet/stock-analysis#10]
股本变迁文件需要写函数进行解析，但是我在项目中的fuc.py并没有找到解析ggbq文件的函数，我看代码中直接是进行pd.csv的读取，前提得是gbbq是csv文件吧

**Comment by wkingnet** [comment]
`readTDX_cw.py`中的`df_gbbq = pytdx.reader.gbbq_reader.GbbqReader().get_df(filepath)`语句
