### ISSUE TITLE
能对分钟数据进行前复权，看到的和通达信的一样吗？

### ISSUE THREAD

**Issue by allon2** [wkingnet/stock-analysis#12]
能对分钟数据进行前复权，看到的和通达信的一样吗？

**Comment by wkingnet** [comment]
> 能对分钟数据进行前复权，看到的和通达信的一样吗？

工具本身不行，代码好像没对分钟数据特别处理。但是复权原理是一样的，你可以看看代码是怎么复权的，自行修改一下
