### ISSUE TITLE
对pandas 3.0的适配

### ISSUE THREAD

**Issue by notanymore** [wkingnet/stock-analysis#15]
当运行func.py:548行的时候，出现以下警告：
C:\stock-analysis-master\func.py:548: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

需要对这行数据操作代码进行更新。

**Comment by wkingnet** [comment]
> 当运行func.py:548行的时候，出现以下警告： C:\stock-analysis-master\func.py:548: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method. The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.
> 
> For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.
> 
> 需要对这行数据操作代码进行更新。

pandans取消`inplace=True`这种表述方法的话，那代码改动的地方太多了。不如anaconda个pandas v1.2.3的环境
