### ISSUE TITLE
报错，大佬能帮忙看看怎么回事吗

### ISSUE THREAD

**Issue by bergkamp2008999** [wkingnet/stock-analysis#2]
D:\Python\Programs\Python\Anaconda3\python.exe "D:/Program Files/JetBrains/PyCharm 2020.1.3/stock-analysis/readTDX_lday.py"
附带命令行参数 readTDX_lday.py del 删除现有文件并重新生成完整数据
处理深市股票
100%|██████████| 2431/2431 [00:00<00:00, 14953.40it/s]
处理沪市股票
100%|██████████| 1903/1903 [00:00<00:00, 15143.41it/s]
处理指数文件
  0%|          | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:/Program Files/JetBrains/PyCharm 2020.1.3/stock-analysis/readTDX_lday.py", line 121, in <module>
    update_lday()
  File "D:/Program Files/JetBrains/PyCharm 2020.1.3/stock-analysis/readTDX_lday.py", line 91, in update_lday
    func.day2csv(ucfg.tdx['tdx_path'] + '/vipdoc/sh/lday', i, ucfg.tdx['csv_index'])
  File "D:\Program Files\JetBrains\PyCharm 2020.1.3\stock-analysis\func.py", line 47, in day2csv
    source_file = open(source_path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'd:/stock/vipdoc/sh/lday\\sh999999.day'

Process finished with exit code 1

**Comment by wkingnet** [comment]
你没有这个文件
FileNotFoundError: [Errno 2] No such file or directory: 'd:/stock/vipdoc/sh/lday\sh999999.day'

这是上证指数日线数据文件。


你先在通达信里完整下载历史数据
![QQ截图20210518133552](https://user-images.githubusercontent.com/57652989/118596172-fae68980-b7dd-11eb-936f-5465dbf8e1c0.png)

**Comment by bergkamp2008999** [comment]
收到，谢谢老大
