### ISSUE TITLE
通达信设置对下载数据前复权不复权有影响吗？

### ISSUE THREAD

**Issue by rovertang** [wkingnet/stock-analysis#9]
如题
个人的尝试：
1、个人在系统设置的设置1中，报表中复权修改为了不复权。
2、也勾选了复权使用等比方式。
然后：下载历史数据。
再：日线分析。(没有修改代码)
结果：获得的是不复权的数据。不过文件夹名字还是_qfq。(对比了数据确认都是不复权)
所以，想问问：我这样下载数据和运行代码，**最终获得的确定是不复权数据吗？**
实际上个人需要的也是不复权数据，因为有财务的分红数据了，所以不想用前复权数据。

**Comment by wkingnet** [comment]
> 如题 个人的尝试： 1、个人在系统设置的设置1中，报表中复权修改为了不复权。 2、也勾选了复权使用等比方式。 然后：下载历史数据。 再：日线分析。(没有修改代码) 结果：获得的是不复权的数据。不过文件夹名字还是_qfq。(对比了数据确认都是不复权) 所以，想问问：我这样下载数据和运行代码，**最终获得的确定是不复权数据吗？** 实际上个人需要的也是不复权数据，因为有财务的分红数据了，所以不想用前复权数据。

1. 通达信的报表复权，这个功能我没注意，不知道是指什么复权，我猜是财务报表数据？
2. 不管通达信怎么设置，用本项目代码运行后默认都是前复权数据，除非你自己修改`readTDX_lday.py`文件。

是否是前复权数据，可以看600000这是股票99年的收盘价：后复权不复权是20多元，等比前复权是1元多，普通前复权是负价格。
